# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: daishodesign CI

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - name: Create env file
        run: |
          echo "Creating .env for ${{ secrets.MAIL_USER }}"
          touch .env
          echo NODE_ENV=production >> .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo MAIL_USER=${{ secrets.MAIL_USER }} >> .env
          echo MAIL_PASS=${{ secrets.MAIL_PASS }} >> .env
          echo MAIL_HOST=${{ secrets.MAIL_HOST }} >> .env
          echo MAIL_PORT=${{ secrets.MAIL_PORT }} >> .env
          echo MAIL_DESTINATION=${{ secrets.MAIL_DESTINATION }} >> .env
          echo POSTMARK_API_TOKEN=${{ secrets.POSTMARK_API_TOKEN }} >> .env
          echo RECAPTCHA_SECRET_KEY=${{ secrets.RECAPTCHA_SECRET_KEY }} >> .env
          cat .env
      - run: npm run build
      - run: cp -r build /var/www/daishodesign/
      # Below: pm2 start npm --name {appName} -- run {script name}
      - run: pm2 start npm --name portfolio_v5 -- run start
      # - run: pm2 restart portfolio_v5 # for continuous deployment
